server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
  port: 80

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SSAFY_DB_URL}
    username: ${SSAFY_DB_USERNAME}
    password: ${SSAFY_DB_PASSWORD}

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
      use_sql_comments: true
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: ${JWT_SECRET}

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}